- Identificación de Valores Nulos: Identifica todas las columnas que contengan valores nulos en el DataFrame.

- Selección de Método de Imputación: Discute en tu compañera cuál sería la mejor estrategia para manejar los valores nulos en cada una de las columnas identificadas en el paso anterior.

- Imputación de Valores Nulos: Implementa el método de imputación seleccionado en el paso 2 para llenar los valores nulos en las columnas.

- Informe: Añade al final de un jupyter una explicación breve que describa las columnas que tenían valores nulos, cómo decidiste imputarlos y cualquier observación adicional que consideres importante sobre el proceso de limpieza de datos.

In [1]:
# importamos las librerías que necesitamos
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np
# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [4]:
df = pd.read_csv("./files/world_data_full_apply.csv", index_col=0)

df.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.230,323.0,32.49,93.0,Kabul,8.672,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.748,9.0,11.78,355.0,Tirana,4.536,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331,Europe
2,Algeria,18.0,DZ,17.4,NaN,317.0,24.28,213.0,Algiers,150.006,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626,Africa
3,Andorra,164.0,AD,40.0,468.000,NaN,7.20,376.0,Andorra la Vella,469.000,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801,Europe
4,Angola,26.0,AO,47.5,NaN,117.0,40.73,244.0,Luanda,34.693,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,-11.202692,17.873887,Africa

In [6]:
# Identificación de Valores Nulos: Identifica todas las columnas que contengan valores nulos en el DataFrame.

df.isna().sum().sort_values(ascending=False)

population                              156
urban_population                        150
minimum_wage                             45
land_area                                30
armed_forces_size                        29
tax_revenue                              26
cpi                                      20
gasoline_price                           20
unemployment_rate                        19
population_labor_force_participation     19
cpi_change                               16
currency-code                            15
maternal_mortality_ratio                 14
total_tax_rate                           12
co2-emissions                            12
gross_tertiary_education_enrollment      12
life_expectancy                           8
physicians_per_thousand                   7
abbreviation                              7
agricultural_land                         7
gross_primary_education_enrollment        7
fertility_rate                            7
out_of_pocket_health_expenditure          7
forested_area                             7
largest_city                              6
infant_mortality                          6
birth_rate                                6
official_language                         5
capital/major_city                        3
gdp                                       2
calling_code                              1
latitude                                  1
longitude                                 1
continent                                 1
country                                   0
density                                   0
dtype: int64

In [7]:
round(df.isna().sum().sort_values(ascending=False)/df.shape[0]*100,2) #sacamos el valor de nulos en porcentajes redondeado a 2 decimales

population                              80.00
urban_population                        76.92
minimum_wage                            23.08
land_area                               15.38
armed_forces_size                       14.87
tax_revenue                             13.33
cpi                                     10.26
gasoline_price                          10.26
unemployment_rate                        9.74
population_labor_force_participation     9.74
cpi_change                               8.21
currency-code                            7.69
maternal_mortality_ratio                 7.18
total_tax_rate                           6.15
co2-emissions                            6.15
gross_tertiary_education_enrollment      6.15
life_expectancy                          4.10
physicians_per_thousand                  3.59
abbreviation                             3.59
agricultural_land                        3.59
gross_primary_education_enrollment       3.59
fertility_rate                           3.59
out_of_pocket_health_expenditure         3.59
forested_area                            3.59
largest_city                             3.08
infant_mortality                         3.08
birth_rate                               3.08
official_language                        2.56
capital/major_city                       1.54
gdp                                      1.03
calling_code                             0.51
latitude                                 0.51
longitude                                0.51
continent                                0.51
country                                  0.00
density                                  0.00
dtype: float64

In [8]:
#Selección de Método de Imputación: Discute en tu compañera cuál sería la mejor estrategia para manejar los valores nulos en cada una de las columnas identificadas en el paso anterior.

In [12]:
df.info() #miramos qué tipo de datos son las columnas con nulos

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 36 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   country                               195 non-null    str
 1   density                               195 non-null    float64
 2   abbreviation                          188 non-null    str
 3   agricultural_land                     188 non-null    float64
 4   land_area                             165 non-null    float64
 5   armed_forces_size                     166 non-null    float64
 6   birth_rate                            189 non-null    float64
 7   calling_code                          194 non-null    float64
 8   capital/major_city                    192 non-null    str
 9   co2-emissions                         183 non-null    float64
 10  cpi                                   175 non-null    float64
 11  cpi_change                            179 non-null    float64
 12  currency-code                         180 non-null    str
 13  fertility_rate                        188 non-null    float64
 14  forested_area                         188 non-null    float64
 15  gasoline_price                        175 non-null    float64
 16  gdp                                   193 non-null    float64
 17  gross_primary_education_enrollment    188 non-null    float64
 18  gross_tertiary_education_enrollment   183 non-null    float64
 19  infant_mortality                      189 non-null    float64
 20  largest_city                          189 non-null    str
 21  life_expectancy                       187 non-null    float64
 22  maternal_mortality_ratio              181 non-null    float64
 23  minimum_wage                          150 non-null    float64
 24  official_language                     190 non-null    str
 25  out_of_pocket_health_expenditure      188 non-null    float64
 26  physicians_per_thousand               188 non-null    float64
 27  population                            39 non-null     float64
 28  population_labor_force_participation  176 non-null    float64
 29  tax_revenue                           169 non-null    float64
 30  total_tax_rate                        183 non-null    float64
 31  unemployment_rate                     176 non-null    float64
 32  urban_population                      45 non-null     float64
 33  latitude                              194 non-null    float64
 34  longitude                             194 non-null    float64
 35  continent                             194 non-null    str
dtypes: float64(29), str(7)
memory usage: 55.0 KB

In [13]:
df.describe(include=np.number).T #sacamos los valores estadísticos para ver si hay variaciones muy amplias entre los datos

,count,mean,std,min,25%,50%,75%,max
density,195.0,1.345045e+02,1.573068e+02,1.265000e+00,2.616850e+01,8.300000e+01,1.655000e+02,8.470000e+02
agricultural_land,188.0,3.911755e+01,2.178305e+01,6.000000e-01,2.170000e+01,3.960000e+01,5.537500e+01,8.260000e+01
land_area,165.0,2.552127e+02,2.583850e+02,0.000000e+00,4.127700e+01,1.484600e+02,4.300000e+02,9.640000e+02
armed_forces_size,166.0,1.037831e+02,1.671580e+02,0.000000e+00,1.025000e+01,2.850000e+01,1.282500e+02,9.360000e+02
birth_rate,189.0,2.021497e+01,9.945774e+00,5.900000e+00,1.130000e+01,1.795000e+01,2.875000e+01,4.608000e+01
calling_code,194.0,3.605464e+02,3.232364e+02,1.000000e+00,8.250000e+01,2.555000e+02,5.067500e+02,1.876000e+03
co2-emissions,183.0,1.259155e+02,1.817949e+02,1.016000e+00,7.600000e+00,3.447700e+01,1.850305e+02,7.279730e+02
cpi,175.0,1.441936e+02,5.478400e+01,9.903000e+01,1.136700e+02,1.247400e+02,1.559250e+02,5.509300e+02
cpi_change,179.0,6.722346e+00,2.445041e+01,-4.300000e+00,1.000000e+00,2.300000e+00,4.250000e+00,2.549000e+02
fertility_rate,188.0,2.698138e+00,1.282267e+00,9.800000e-01,1.705000e+00,2.245000e+00,3.597500e+00,6.910000e+00
forested_area,188.0,3.201543e+01,2.379133e+01,0.000000e+00,1.100000e+01,3.200000e+01,4.817500e+01,9.830000e+01
gasoline_price,175.0,1.002457e+00,3.688585e-01,0.000000e+00,7.550000e-01,9.800000e-01,1.240000e+00,2.000000e+00
gdp,193.0,4.772959e+11,2.172173e+12,4.727146e+07,8.454620e+09,3.438723e+10,2.340940e+11,2.142770e+13
gross_primary_education_enrollment,188.0,1.024702e+02,1.315161e+01,2.340000e+01,9.895000e+01,1.025500e+02,1.080250e+02,1.425000e+02
gross_tertiary_education_enrollment,183.0,3.796339e+01,2.926102e+01,8.000000e-01,1.215000e+01,3.120000e+01,6.315000e+01,1.366000e+02
infant_mortality,189.0,2.133280e+01,1.954806e+01,1.400000e+00,6.000000e+00,1.400000e+01,3.270000e+01,8.450000e+01
life_expectancy,187.0,7.227968e+01,7.483661e+00,5.280000e+01,6.700000e+01,7.320000e+01,7.750000e+01,8.540000e+01
maternal_mortality_ratio,181.0,1.603923e+02,2.335020e+02,2.000000e+00,1.300000e+01,5.300000e+01,1.860000e+02,1.150000e+03
minimum_wage,150.0,2.194133e+00,2.970796e+00,1.000000e-02,4.025000e-01,1.045000e+00,2.447500e+00,1.359000e+01
out_of_pocket_health_expenditure,188.0,3.263723e+01,1.917270e+01,2.000000e-01,1.745000e+01,3.070000e+01,4.397500e+01,8.160000e+01
physicians_per_thousand,188.0,1.839840e+00,1.684261e+00,1.000000e-02,3.325000e-01,1.460000e+00,2.935000e+00,8.420000e+00
population,39.0,3.335427e+02,2.964675e+02,1.008400e+01,8.713000e+01,2.150560e+02,5.561625e+02,9.735600e+02
population_labor_force_participation,176.0,6.273807e+01,1.050291e+01,3.800000e+01,5.615000e+01,6.245000e+01,6.950000e+01,8.680000e+01
tax_revenue,169.0,1.657396e+01,6.961632e+00,0.000000e+00,1.170000e+01,1.630000e+01,2.110000e+01,3.720000e+01
total_tax_rate,183.0,4.082240e+01,2.055766e+01,8.000000e+00,3.060000e+01,3.720000e+01,4.800000e+01,2.196000e+02
unemployment_rate,176.0,6.886364e+00,5.079216e+00,9.000000e-02,3.395000e+00,5.360000e+00,9.490000e+00,2.818000e+01
urban_population,45.0,2.794610e+02,2.833224e+02,5.464000e+00,4.076500e+01,1.790390e+02,4.177650e+02,9.848120e+02
latitude,194.0,1.909235e+01,2.396178e+01,-4.090056e+01,4.544175e+00,1.727385e+01,4.012460e+01,6.496305e+01
longitude,194.0,2.023243e+01,6.671611e+01,-1.751982e+02,-7.941496e+00,2.097265e+01,4.828152e+01,1.780650e+02

In [28]:
df[["largest_city","capital/major_city","population","unemployment_rate"]]

         largest_city capital/major_city  population  unemployment_rate
0               Kabul              Kabul         NaN              11.12
1              Tirana             Tirana         NaN              12.33
2             Algiers            Algiers         NaN              11.70
3    Andorra la Vella   Andorra la Vella      77.142                NaN
4              Luanda             Luanda         NaN               6.89
..                ...                ...         ...                ...
190           Caracas            Caracas         NaN               8.80
191  Ho Chi Minh City              Hanoi         NaN               2.01
192             Sanaa              Sanaa         NaN              12.91
193            Lusaka             Lusaka         NaN              11.43
194            Harare             Harare         NaN               4.95

[195 rows x 4 columns]

In [29]:
df[["population","capital/major_city", "unemployment_rate"]]

     population capital/major_city  unemployment_rate
0           NaN              Kabul              11.12
1           NaN             Tirana              12.33
2           NaN            Algiers              11.70
3        77.142   Andorra la Vella                NaN
4           NaN             Luanda               6.89
..          ...                ...                ...
190         NaN            Caracas               8.80
191         NaN              Hanoi               2.01
192         NaN              Sanaa              12.91
193         NaN             Lusaka              11.43
194         NaN             Harare               4.95

[195 rows x 3 columns]

In [30]:
df["population"].mode()[0]

np.float64(10.084)

In [51]:
# Podemos ver la cantidad de nulos por continente y ver si podemos analizar muestras por alguno concreto.

In [32]:
df[[ "minimum_wage","gross_primary_education_enrollment","gross_tertiary_education_enrollment"]]

,minimum_wage,gross_primary_education_enrollment,gross_tertiary_education_enrollment
0,0.43,104.0,9.7
1,1.12,107.0,55.0
2,0.95,109.9,51.4
3,6.63,106.4,NaN
4,0.71,113.5,9.3
...,...,...,...
190,0.01,97.2,79.3
191,0.73,110.6,28.5
192,NaN,93.6,10.2
193,0.24,98.7,4.1
194,NaN,109.9,10.0

In [35]:
df.groupby(["gross_primary_education_enrollment","gross_tertiary_education_enrollment"])["minimum_wage"].mean()[:20]

gross_primary_education_enrollment  gross_tertiary_education_enrollment
23.4                                2.5                                     NaN
61.8                                1.9                                    1.05
68.4                                3.4                                     NaN
74.7                                4.4                                    0.29
75.3                                5.3                                     NaN
75.6                                4.5                                    0.23
76.8                                16.9                                   0.41
81.0                                12.8                                   0.31
81.4                                15.1                                   5.25
81.5                                34.4                                   1.49
81.7                                40.1                                   1.02
84.7                                10.2                                   0.54
                                    23.7                                   2.00
85.1                                11.9                                   0.17
85.2                                49.4                                   2.25
86.8                                3.3                                    0.60
88.4                                8.0                                    0.88
89.3                                71.0                                   1.57
90.6                                39.8                                   0.31
91.0                                27.1                                   1.33
Name: minimum_wage, dtype: float64

In [38]:
df.groupby(["gross_primary_education_enrollment","gross_tertiary_education_enrollment"])["minimum_wage"].describe()[:20]

                                                                        count  \
gross_primary_education_enrollment gross_tertiary_education_enrollment
23.4                               2.5                                    0.0
61.8                               1.9                                    1.0
68.4                               3.4                                    0.0
74.7                               4.4                                    1.0
75.3                               5.3                                    0.0
75.6                               4.5                                    1.0
76.8                               16.9                                   1.0
81.0                               12.8                                   1.0
81.4                               15.1                                   1.0
81.5                               34.4                                   1.0
81.7                               40.1                                   1.0
84.7                               10.2                                   1.0
                                   23.7                                   1.0
85.1                               11.9                                   1.0
85.2                               49.4                                   1.0
86.8                               3.3                                    1.0
88.4                               8.0                                    1.0
89.3                               71.0                                   1.0
90.6                               39.8                                   1.0
91.0                               27.1                                   1.0

                                                                        mean  \
gross_primary_education_enrollment gross_tertiary_education_enrollment
23.4                               2.5                                   NaN
61.8                               1.9                                  1.05
68.4                               3.4                                   NaN
74.7                               4.4                                  0.29
75.3                               5.3                                   NaN
75.6                               4.5                                  0.23
76.8                               16.9                                 0.41
81.0                               12.8                                 0.31
81.4                               15.1                                 5.25
81.5                               34.4                                 1.49
81.7                               40.1                                 1.02
84.7                               10.2                                 0.54
                                   23.7                                 2.00
85.1                               11.9                                 0.17
85.2                               49.4                                 2.25
86.8                               3.3                                  0.60
88.4                               8.0                                  0.88
89.3                               71.0                                 1.57
90.6                               39.8                                 0.31
91.0                               27.1                                 1.33

                                                                        std  \
gross_primary_education_enrollment gross_tertiary_education_enrollment
23.4                               2.5                                  NaN
61.8                               1.9                                  NaN
68.4                               3.4                                  NaN
74.7                               4.4                                  NaN
75.3                               5.3                                  NaN
75.6                               4.5                                  NaN
76.8                               16.9                                 NaN
81.0                               12.8                                 NaN
81.4                               15.1                                 NaN
81.5                               34.4                                 NaN
81.7                               40.1                                 NaN
84.7                               10.2                                 NaN
                                   23.7                                 NaN
85.1                               11.9                                 NaN
85.2                               49.4                                 NaN
86.8                               3.3                                  NaN
88.4                               8.0                                  NaN
89.3                               71.0                                 NaN
90.6                               39.8                                 NaN
91.0                               27.1                                 NaN

                                                                         min  \
gross_primary_education_enrollment gross_tertiary_education_enrollment
23.4                               2.5                                   NaN
61.8                               1.9                                  1.05
68.4                               3.4                                   NaN
74.7                               4.4                                  0.29
75.3                               5.3                                   NaN
75.6                               4.5                                  0.23
76.8                               16.9                                 0.41
81.0                               12.8                                 0.31
81.4                               15.1                                 5.25
81.5                               34.4                                 1.49
81.7                               40.1                                 1.02
84.7                               10.2                                 0.54
                                   23.7                                 2.00
85.1                               11.9                                 0.17
85.2                               49.4                                 2.25
86.8                               3.3                                  0.60
88.4                               8.0                                  0.88
89.3                               71.0                                 1.57
90.6                               39.8                                 0.31
91.0                               27.1                                 1.33

                                                                         25%  \
gross_primary_education_enrollment gross_tertiary_education_enrollment
23.4                               2.5                                   NaN
61.8                               1.9                                  1.05
68.4                               3.4                                   NaN
74.7                               4.4                                  0.29
75.3                               5.3                                   NaN
75.6                               4.5                                  0.23
76.8                               16.9                                 0.41
81.0                               12.8                                 0.31
81.4                               15.1                                 5.25
81.5                               34.4                                 1.49
81.7                               40.1                                 1.02
84.7                               10.2                                 0.54
                                   23.7                                 2.00
85.1                               11.9                                 0.17
85.2                               49.4                                 2.25
86.8                               3.3                                  0.60
88.4                               8.0                                  0.88
89.3                               71.0                                 1.57
90.6                               39.8                                 0.31
91.0                               27.1                                 1.33

                                                                         50%  \
gross_primary_education_enrollment gross_tertiary_education_enrollment
23.4                               2.5                                   NaN
61.8                               1.9                                  1.05
68.4                               3.4                                   NaN
74.7                               4.4                                  0.29
75.3                               5.3                                   NaN
75.6                               4.5                                  0.23
76.8                               16.9                                 0.41
81.0                               12.8                                 0.31
81.4                               15.1                                 5.25
81.5                               34.4                                 1.49
81.7                               40.1                                 1.02
84.7                               10.2                                 0.54
                                   23.7                                 2.00
85.1                               11.9                                 0.17
85.2                               49.4                                 2.25
86.8                               3.3                                  0.60
88.4                               8.0                                  0.88
89.3                               71.0                                 1.57
90.6                               39.8                                 0.31
91.0                               27.1                                 1.33

                                                                         75%  \
gross_primary_education_enrollment gross_tertiary_education_enrollment
23.4                               2.5                                   NaN
61.8                               1.9                                  1.05
68.4                               3.4                                   NaN
74.7                               4.4                                  0.29
75.3                               5.3                                   NaN
75.6                               4.5                                  0.23
76.8                               16.9                                 0.41
81.0                               12.8                                 0.31
81.4                               15.1                                 5.25
81.5                               34.4                                 1.49
81.7                               40.1                                 1.02
84.7                               10.2                                 0.54
                                   23.7                                 2.00
85.1                               11.9                                 0.17
85.2                               49.4                                 2.25
86.8                               3.3                                  0.60
88.4                               8.0                                  0.88
89.3                               71.0                                 1.57
90.6                               39.8                                 0.31
91.0                               27.1                                 1.33

                                                                         max
gross_primary_education_enrollment gross_tertiary_education_enrollment
23.4                               2.5                                   NaN
61.8                               1.9                                  1.05
68.4                               3.4                                   NaN
74.7                               4.4                                  0.29
75.3                               5.3                                   NaN
75.6                               4.5                                  0.23
76.8                               16.9                                 0.41
81.0                               12.8                                 0.31
81.4                               15.1                                 5.25
81.5                               34.4                                 1.49
81.7                               40.1                                 1.02
84.7                               10.2                                 0.54
                                   23.7                                 2.00
85.1                               11.9                                 0.17
85.2                               49.4                                 2.25
86.8                               3.3                                  0.60
88.4                               8.0                                  0.88
89.3                               71.0                                 1.57
90.6                               39.8                                 0.31
91.0                               27.1                                 1.33

In [ ]:
df.groupby("gross_primary_education_enrollment")["minimum_wage"].count() #ojo con hacer agrupaciones con variables conntinuas, no tiene sentido la media, mediana...

gross_primary_education_enrollment
23.4     0
61.8     1
68.4     0
73.0     0
74.7     1
        ..
126.6    0
133.0    0
139.9    1
142.1    1
142.5    2
Name: minimum_wage, Length: 141, dtype: int64

In [ ]:
df.groupby("gross_tertiary_education_enrollment")["minimum_wage"].mean()

gross_tertiary_education_enrollment
0.8      1
1.1      1
1.8      1
1.9      1
2.0      1
        ..
90.0     1
94.3     1
104.6    0
113.1    1
136.6    1
Name: minimum_wage, Length: 171, dtype: int64

In [49]:
df.groupby("continent")["minimum_wage"].count()

continent
Africa             40
Asia               35
Central America    18
Europe             34
North America       2
Oceania             9
South America      12
Name: minimum_wage, dtype: int64

In [50]:
df.groupby("continent")["minimum_wage"].mean()

continent
Africa             0.530000
Asia               1.458571
Central America    1.587778
Europe             4.606176
North America      8.380000
Oceania            3.917778
South America      1.638333
Name: minimum_wage, dtype: float64