- Explora y carga ambos conjuntos de datos en pandas DataFrames. "world-data-2023-part1.csv" y "world-data-2023-part2.csv",
- Identifica las columnas comunes entre los dos conjuntos de datos.
- Utiliza el método de unión de Pandas que consideres más adecuado para combinar los datos de ambos años en un solo DataFrame.
- Explica por qué elegiste ese método de unión y cómo se llevaron a cabo los pasos anteriores.

In [92]:
import pandas as pd
import numpy as np

In [93]:
pd.set_option("display.max_columns",None) #display todas las columnas

In [ ]:
df_wd2023_1 = pd.read_csv("files/world-data-2023_part1.csv",index_col=0)

df_wd2023_1.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [ ]:
df_wd2023_2 = pd.read_csv("files/world-data-2023_part2.csv",index_col=0)

df_wd2023_2.head()

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"
3,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",Andorra,"('42.506285 ', '1.521801')"
4,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",Angola,"('-11.202692 ', '17.873887')"

In [96]:
pd.Series(df_wd2023_1.columns) #comprueba si las columnas de un df están en el otro

0                   Country
1          Density\n(P/Km2)
2              Abbreviation
3     Agricultural Land( %)
4            Land Area(Km2)
5         Armed Forces size
6                Birth Rate
7              Calling Code
8        Capital/Major City
9             Co2-Emissions
10                      CPI
11           CPI Change (%)
12            Currency-Code
13           Fertility Rate
14        Forested Area (%)
15           Gasoline Price
dtype: str

In [97]:
pd.Series(df_wd2023_2.columns)

0                                           GDP
1        Gross primary education enrollment (%)
2       Gross tertiary education enrollment (%)
3                              Infant mortality
4                                  Largest city
5                               Life expectancy
6                      Maternal mortality ratio
7                                  Minimum wage
8                             Official language
9              Out of pocket health expenditure
10                      Physicians per thousand
11                                   Population
12    Population: Labor force participation (%)
13                              Tax revenue (%)
14                               Total tax rate
15                            Unemployment rate
16                             Urban_population
17                                      country
18                                  coordinates
dtype: str

In [98]:
#- Identifica las columnas comunes entre los dos conjuntos de datos.

## Después de examinar los datos, vemos las siguientes coincidencias:

- Country vs country (1,2)
- Capital/Major City vs Largest city (1,2)

In [99]:
#Utiliza el método de unión de Pandas que consideres más adecuado para combinar los datos de ambos años en un solo DataFrame.

In [100]:
df_wd2023_1.merge(df_wd2023_2,left_on=["Country","Capital/Major City"],right_on=["country","Largest city"]).head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"

In [101]:
df_wd2023 = df_wd2023_1.merge(df_wd2023_2,left_on=["Country","Capital/Major City"],right_on=["country","Largest city"]) #guardamos cambios en la variable

In [102]:
df_wd2023.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"

#Explica por qué elegiste ese método de unión y cómo se llevaron a cabo los pasos anteriores.

Hemos elegido merge al tener columnas comunes entre ambos dataframes, aunque con nombres diferentes. Hemos indicado que la unión se realice a través de las columnas "Country" y "Capital/Major City" del primer dataframe y "country" y "Largest city" del segundo dataframe. De esta forma, se han combinado los datos de ambos años en un solo DataFrame, manteniendo solo las filas que tienen coincidencias en ambas tablas.

## Ejercicios de Limpieza

In [103]:
# 1. Después de la unión de datos, tenemos dos columnas de "country". Elimina una de ellas.

In [104]:
df_wd2023.drop(columns="country",inplace=True) #elimina la columna "country" y guarda los cambios en la variable

In [105]:
df_wd2023.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"

## Los nombres de las columnas no son homogeneos. Cambia los nombres de las columnas de tal forma que:

    - No tengan espacios. X
    - Estén en minúscula. X
    - No tengan paréntesis, es decir, quitar "(%)", "(Km2)".
    - Algunas columnas tiene "\n". Eliminalos de los nombres de las columnas.
    - Algunas columnas tienen ":". Eliminalos de los nombres de las columnas.

In [106]:
nuevas_columnas = {columna: columna.lower().replace(" ","") for columna in df_wd2023.columns} #vamos a iterar por todas las columnas del DataFrame y a cada una de ellas la pondremos en minúsula y le aplicaremos un replace para quitar los puntos. 
  
#todo minuscula y sin espacios
#comprobamos que hemos creado el diccionario correctamente
nuevas_columnas

# una vez que tenemos el diccionario vamos a aplicar el método rename
df_wd2023.rename(columns = nuevas_columnas, inplace = True)

df_wd2023.head(2)

,country,density\n(p/km2),abbreviation,agriculturalland(%),landarea(km2),armedforcessize,birthrate,callingcode,capital/majorcity,co2-emissions,cpi,cpichange(%),currency-code,fertilityrate,forestedarea(%),gasolineprice,gdp,grossprimaryeducationenrollment(%),grosstertiaryeducationenrollment(%),infantmortality,largestcity,lifeexpectancy,maternalmortalityratio,minimumwage,officiallanguage,outofpockethealthexpenditure,physiciansperthousand,population,population:laborforceparticipation(%),taxrevenue(%),totaltaxrate,unemploymentrate,urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"

In [107]:
#PRIMERA PRUEBA. iteramos en busqueda de la solución.
for c in df_wd2023.columns:
        print (c.split("(")[0].strip().replace(":","").lower())

country
density
abbreviation
agriculturalland
landarea
armedforcessize
birthrate
callingcode
capital/majorcity
co2-emissions
cpi
cpichange
currency-code
fertilityrate
forestedarea
gasolineprice
gdp
grossprimaryeducationenrollment
grosstertiaryeducationenrollment
infantmortality
largestcity
lifeexpectancy
maternalmortalityratio
minimumwage
officiallanguage
outofpockethealthexpenditure
physiciansperthousand
population
populationlaborforceparticipation
taxrevenue
totaltaxrate
unemploymentrate
urban_population
coordinates

In [108]:
#split por la parte de apertura y nos quedamos con la parte izquierda.

nuevas_columnas2 = {c: c.split("(")[0].strip().replace(":","").lower() for c in df_wd2023.columns} #strip quita el \n

nuevas_columnas2

# una vez que tenemos el diccionario vamos a aplicar el método rename
df_wd2023.rename(columns = nuevas_columnas2, inplace = True)

df_wd2023.head(2)

,country,density,abbreviation,agriculturalland,landarea,armedforcessize,birthrate,callingcode,capital/majorcity,co2-emissions,cpi,cpichange,currency-code,fertilityrate,forestedarea,gasolineprice,gdp,grossprimaryeducationenrollment,grosstertiaryeducationenrollment,infantmortality,largestcity,lifeexpectancy,maternalmortalityratio,minimumwage,officiallanguage,outofpockethealthexpenditure,physiciansperthousand,population,populationlaborforceparticipation,taxrevenue,totaltaxrate,unemploymentrate,urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"

In [109]:
#3. La columnas coordinates tiene la latitud y la longitud en una sola columna. Crea dos columnas nuevas, una con la longitud y otra con la latitud. 
# Una vez hecho, elimina la columna de coordinates.

df_wd2023["coordinates"].str.split(",",  expand = True) #hacemos split y mostramos, cambios no realizados.

df_wd2023[["longitud", "latitud"]] = df_wd2023["coordinates"].str.split(",", expand = True).get([0,1])

In [110]:
df_wd2023.head(2)

,country,density,abbreviation,agriculturalland,landarea,armedforcessize,birthrate,callingcode,capital/majorcity,co2-emissions,cpi,cpichange,currency-code,fertilityrate,forestedarea,gasolineprice,gdp,grossprimaryeducationenrollment,grosstertiaryeducationenrollment,infantmortality,largestcity,lifeexpectancy,maternalmortalityratio,minimumwage,officiallanguage,outofpockethealthexpenditure,physiciansperthousand,population,populationlaborforceparticipation,taxrevenue,totaltaxrate,unemploymentrate,urban_population,coordinates,longitud,latitud
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')",('33.93911 ','67.709953')
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')",('41.153332 ','20.168331')