In [30]:
import pandas as pd
import numpy as np

In [31]:
pd.set_option("display.max_columns", None)

In [32]:
df_wdata = pd.read_csv("files/world_data_full.csv", index_col=0)

df_wdata.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
0,Afghanistan,60,AF,58.1,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.3,AFN,4.47,2.1,0.70,"19,101,353,833",104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,"38,041,754",48.9,9.3,71.4,11.12,"9,797,273",33.93911,67.709953
1,Albania,105,AL,43.1,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.4,ALL,1.62,28.1,1.36,"15,278,077,447",107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,"2,854,191",55.7,18.6,36.6,12.33,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.4,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.0,DZD,3.02,0.8,0.28,"169,988,236,398",109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,"43,053,054",41.2,37.2,66.1,11.70,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.0,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.0,1.51,"3,154,057,987",106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.5,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.1,AOA,5.52,46.3,0.97,"94,635,415,870",113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,"31,825,295",77.5,9.2,49.1,6.89,"21,061,025",-11.202692,17.873887

## Ejercicios 'apply'

In [33]:
# Ejercicio 1: Las columnas land_area, armed_forces_size, co2-emissions, gdp, population, urban_population, latitude, longitude, density, cpi son de tipo object pero en realidad deberían ser numéricas. 
# Crea una función que nos permita cambiar el tipo de dato de estas columnas al que le corresponde.

df_wdata[["land_area", "armed_forces_size", "co2-emissions", "gdp", "population", "urban_population", "latitude", "longitude", "density", "cpi"]].head()

# land_area + gdp + population + urban_population -> int
# armed_forces_size + co2-emissions + cpi -> float

,land_area,armed_forces_size,co2-emissions,gdp,population,urban_population,latitude,longitude,density,cpi
0,"652,230","323,000","8,672","19,101,353,833","38,041,754","9,797,273",33.93911,67.709953,60,149.9
1,"28,748","9,000","4,536","15,278,077,447","2,854,191","1,747,593",41.153332,20.168331,105,119.05
2,"2,381,741","317,000","150,006","169,988,236,398","43,053,054","31,510,100",28.033886,1.659626,18,151.36
3,468,NaN,469,"3,154,057,987","77,142","67,873",42.506285,1.521801,164,NaN
4,"1,246,700","117,000","34,693","94,635,415,870","31,825,295","21,061,025",-11.202692,17.873887,26,261.73

In [34]:
# info original
df_wdata.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   country                               195 non-null    str
 1   density                               195 non-null    str
 2   abbreviation                          188 non-null    str
 3   agricultural_land                     188 non-null    float64
 4   land_area                             194 non-null    str
 5   armed_forces_size                     171 non-null    str
 6   birth_rate                            189 non-null    float64
 7   calling_code                          194 non-null    float64
 8   capital/major_city                    192 non-null    str
 9   co2-emissions                         188 non-null    str
 10  cpi                                   178 non-null    str
 11  cpi_change                            179 non-null    float64
 12  currency-code                         180 non-null    str
 13  fertility_rate                        188 non-null    float64
 14  forested_area                         188 non-null    float64
 15  gasoline_price                        175 non-null    float64
 16  gdp                                   193 non-null    str
 17  gross_primary_education_enrollment    188 non-null    float64
 18  gross_tertiary_education_enrollment   183 non-null    float64
 19  infant_mortality                      189 non-null    float64
 20  largest_city                          189 non-null    str
 21  life_expectancy                       187 non-null    float64
 22  maternal_mortality_ratio              181 non-null    float64
 23  minimum_wage                          150 non-null    float64
 24  official_language                     190 non-null    str
 25  out_of_pocket_health_expenditure      188 non-null    float64
 26  physicians_per_thousand               188 non-null    float64
 27  population                            194 non-null    str
 28  population_labor_force_participation  176 non-null    float64
 29  tax_revenue                           169 non-null    float64
 30  total_tax_rate                        183 non-null    float64
 31  unemployment_rate                     176 non-null    float64
 32  urban_population                      190 non-null    str
 33  latitude                              195 non-null    str
 34  longitude                             195 non-null    str
dtypes: float64(19), str(16)
memory usage: 53.4 KB

In [35]:
def cambio_int(nombre):
    try:
        return int(nombre.replace(",","").replace(".",""))
    
    except:
        return nombre 
    
def cambio_float(nombre):
    try:
        return float(nombre.replace(",","").replace(".",""))
    
    except:
        return nombre

In [36]:
# Pruebas
print(cambio_int("652,230"))
print(cambio_float("323,000"))

652230
323000.0

In [37]:
col_int = ["land_area", "gdp", "population", "urban_population"]

In [38]:
# land_area + gdp + population + urban_population -> int

for columna in col_int:

    df_wdata[columna] =  df_wdata[columna].apply(cambio_int)

In [39]:
df_wdata.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   country                               195 non-null    str
 1   density                               195 non-null    str
 2   abbreviation                          188 non-null    str
 3   agricultural_land                     188 non-null    float64
 4   land_area                             194 non-null    float64
 5   armed_forces_size                     171 non-null    str
 6   birth_rate                            189 non-null    float64
 7   calling_code                          194 non-null    float64
 8   capital/major_city                    192 non-null    str
 9   co2-emissions                         188 non-null    str
 10  cpi                                   178 non-null    str
 11  cpi_change                            179 non-null    float64
 12  currency-code                         180 non-null    str
 13  fertility_rate                        188 non-null    float64
 14  forested_area                         188 non-null    float64
 15  gasoline_price                        175 non-null    float64
 16  gdp                                   193 non-null    float64
 17  gross_primary_education_enrollment    188 non-null    float64
 18  gross_tertiary_education_enrollment   183 non-null    float64
 19  infant_mortality                      189 non-null    float64
 20  largest_city                          189 non-null    str
 21  life_expectancy                       187 non-null    float64
 22  maternal_mortality_ratio              181 non-null    float64
 23  minimum_wage                          150 non-null    float64
 24  official_language                     190 non-null    str
 25  out_of_pocket_health_expenditure      188 non-null    float64
 26  physicians_per_thousand               188 non-null    float64
 27  population                            194 non-null    float64
 28  population_labor_force_participation  176 non-null    float64
 29  tax_revenue                           169 non-null    float64
 30  total_tax_rate                        183 non-null    float64
 31  unemployment_rate                     176 non-null    float64
 32  urban_population                      190 non-null    float64
 33  latitude                              195 non-null    str
 34  longitude                             195 non-null    str
dtypes: float64(23), str(12)
memory usage: 53.4 KB

In [40]:
col_float = ["armed_forces_size", "co2-emissions", "cpi"]

In [41]:
# armed_forces_size + co2-emissions + cpi -> float

for columna in col_float:

    df_wdata[columna] =  df_wdata[columna].apply(cambio_float)

In [42]:
df_wdata.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   country                               195 non-null    str
 1   density                               195 non-null    str
 2   abbreviation                          188 non-null    str
 3   agricultural_land                     188 non-null    float64
 4   land_area                             194 non-null    float64
 5   armed_forces_size                     171 non-null    float64
 6   birth_rate                            189 non-null    float64
 7   calling_code                          194 non-null    float64
 8   capital/major_city                    192 non-null    str
 9   co2-emissions                         188 non-null    float64
 10  cpi                                   178 non-null    float64
 11  cpi_change                            179 non-null    float64
 12  currency-code                         180 non-null    str
 13  fertility_rate                        188 non-null    float64
 14  forested_area                         188 non-null    float64
 15  gasoline_price                        175 non-null    float64
 16  gdp                                   193 non-null    float64
 17  gross_primary_education_enrollment    188 non-null    float64
 18  gross_tertiary_education_enrollment   183 non-null    float64
 19  infant_mortality                      189 non-null    float64
 20  largest_city                          189 non-null    str
 21  life_expectancy                       187 non-null    float64
 22  maternal_mortality_ratio              181 non-null    float64
 23  minimum_wage                          150 non-null    float64
 24  official_language                     190 non-null    str
 25  out_of_pocket_health_expenditure      188 non-null    float64
 26  physicians_per_thousand               188 non-null    float64
 27  population                            194 non-null    float64
 28  population_labor_force_participation  176 non-null    float64
 29  tax_revenue                           169 non-null    float64
 30  total_tax_rate                        183 non-null    float64
 31  unemployment_rate                     176 non-null    float64
 32  urban_population                      190 non-null    float64
 33  latitude                              195 non-null    str
 34  longitude                             195 non-null    str
dtypes: float64(26), str(9)
memory usage: 53.4 KB

In [43]:
df_wdata[["land_area", "armed_forces_size", "co2-emissions", "gdp", "population", "urban_population", "latitude", "longitude", "density", "cpi"]].head()

,land_area,armed_forces_size,co2-emissions,gdp,population,urban_population,latitude,longitude,density,cpi
0,652230.0,323000.0,8672.0,1.910135e+10,38041754.0,9797273.0,33.93911,67.709953,60,1499.0
1,28748.0,9000.0,4536.0,1.527808e+10,2854191.0,1747593.0,41.153332,20.168331,105,11905.0
2,2381741.0,317000.0,150006.0,1.699882e+11,43053054.0,31510100.0,28.033886,1.659626,18,15136.0
3,468.0,NaN,469.0,3.154058e+09,77142.0,67873.0,42.506285,1.521801,164,NaN
4,1246700.0,117000.0,34693.0,9.463542e+10,31825295.0,21061025.0,-11.202692,17.873887,26,26173.0

In [44]:
# Ejercicio 2: Crea una función para añadir una nueva columna llamada 'Continent' al DataFrame para indicar a qué continente pertenece cada país.

In [45]:
print(df_wdata["country"].unique())

<StringArray>
[        'Afghanistan',             'Albania',             'Algeria',
             'Andorra',              'Angola', 'Antigua and Barbuda',
           'Argentina',             'Armenia',           'Australia',
             'Austria',
 ...
      'United Kingdom',       'United States',             'Uruguay',
          'Uzbekistan',             'Vanuatu',           'Venezuela',
             'Vietnam',               'Yemen',              'Zambia',
            'Zimbabwe']
Length: 195, dtype: str

In [46]:
# Para ver TODOS los nombres de países: print(df_wdata["Continent"].to_list())

In [47]:
continentes = {
    'Asia': ["Philippines", 'Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'East Timor', 'India', 'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'North Korea', 'Oman', 'Pakistan', 'Palestinian National Authority', 'Qatar', 'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Tajikistan', 'Thailand', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen'],
    'Africa': ["Tunisia", "Ivory Coast", 'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cape Verde', 'Cameroon', 'Central African Republic', 'Chad', 'Comoros', 'Republic of the Congo', 'Cote d\'Ivoire', 'Democratic Republic of the Congo', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon', 'The Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Tanzania', 'Togo', 'Uganda', 'Zambia', 'Zimbabwe'],
    'Europe': ["Turkey", "Republic of Ireland", "Vatican City", 'Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Ukraine', 'United Kingdom'],
    "Central America":["Belize", "Saint Vincent and the Grenadines", "Saint Lucia", "Saint Kitts and Nevis", "Panama", "Nicaragua", "Mexico", "Jamaica", "Honduras", "Haiti", "Guatemala", "Grenada", "El Salvador", "Dominican Republic", "Dominica", "Cuba", "Antigua and Barbuda", "The Bahamas", "Barbados"," Belize", "Costa Rica",  ],
    'North America': ['Canada', 'United States'],'South America': ["Trinidad and Tobago", 'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela'],
    'Oceania': ["Papua New Guinea", "Federated States of Micronesia", 'Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Nauru', 'New Zealand', 'Palau', 'Samoa', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu']}

In [48]:
def pais_cont(nombre):
    try:
        for continente, paises in continentes.items():
            if nombre in paises:
                return continente
        
    except:
        return nombre

In [49]:
df_wdata["Continent"] = df_wdata["country"].apply(pais_cont)

In [50]:
df_wdata["Continent"]

0               Asia
1             Europe
2             Africa
3             Europe
4             Africa
           ...
190    South America
191             Asia
192             Asia
193           Africa
194           Africa
Name: Continent, Length: 195, dtype: str