## Ejercicios de exploración del conjunto de datos

En este fichero encontraremos la siguiente información:

- Country:  Nombre del país.

- Density\n(P/Km2): Densidad de población medida en personas por kilómetro cuadrado.

- Abbreviation: Abreviatura o código que representa al país.

- Agricultural Land( %): Porcentaje del área total de tierra utilizada con fines agrícolas.

- Land Area(Km2): Área total de tierra del país en kilómetros cuadrados.

- Armed Forces size: Tamaño de las fuerzas armadas en el país.

- Birth Rate: Número de nacimientos por cada 1,000 habitantes por año.

- Calling Code: Código internacional de llamada para el país.

- Capital/Major City: Nombre de la capital o ciudad principal.

- Co2-Emissions: Emisiones de dióxido de carbono en toneladas.

- CPI: Índice de Precios al Consumidor (IPC), una medida de la inflación y el poder adquisitivo.

- CPI Change (%): Cambio porcentual en el Índice de Precios al Consumidor en comparación con el año anterior.

- Currency-Code: Código de moneda utilizado en el país.

- Fertility Rate: Número promedio de hijos nacidos de una mujer durante su vida.

- Forested Area (%): Porcentaje del área total cubierta por bosques.

- Gasoline Price: Precio de la gasolina por litro en moneda local.

In [14]:
# Importamos liberaría de Pandas

import pandas as pd

In [15]:
# Abrimos el documento 

df_mundo = pd.read_csv("files/world-data-2023_part1.csv", index_col=0)

In [16]:
# Ejercicio 1: Muestra las primeras 5 filas del conjunto de datos.

df_mundo.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [17]:
# Ejercicio 2: Muestra las últimas 5 filas del conjunto de datos.

df_mundo.tail()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

In [18]:
# Ejercicio 3: Muestra una muestra aleatoria de 5 filas del conjunto de datos.

df_mundo.sample(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
124,Nicaragua,55,NI,42.10%,"130,370","12,000",20.64,505.0,Managua,"5,592",162.74,5.40%,NIO,2.40,25.90%,$0.91
117,Mozambique,40,MZ,63.50%,"799,380","11,000",37.52,258.0,Maputo,"7,943",182.31,2.80%,MZN,4.85,48.00%,$0.65
94,Lebanon,667,LB,64.30%,"10,400","80,000",17.55,961.0,Beirut,"24,796",130.02,3.00%,LBP,2.09,13.40%,$0.74
33,Central African Republic,8,CF,8.20%,"622,984","8,000",35.35,236.0,Bangui,297,186.86,37.10%,NaN,4.72,35.60%,$1.41
135,Papua New Guinea,20,PG,2.60%,"462,840","4,000",27.07,675.0,Port Moresby,"7,536",155.99,3.60%,PGK,3.56,74.10%,$1.36

In [28]:
# Ejercicio 4: Muestra el nombre de todas las columnas en el conjunto de datos.

df_mundo.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price'],
      dtype='str')

In [29]:
# Ejercicio 5: Muestra los valores únicos en la columna "Abbreviation".

df_mundo["Abbreviation"].unique()

<StringArray>
['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT',
 ...
 'GB', 'US', 'UY', 'UZ', 'VU', 'VE', 'VN', 'YE', 'ZM', 'ZW']
Length: 189, dtype: str

In [34]:
# Ejercicio 6: Cuenta cuántas veces aparece cada valor único en la columna "Abbreviation".

df_mundo["Abbreviation"].unique().value_counts()

AF    1
AL    1
DZ    1
AD    1
AO    1
     ..
VE    1
VN    1
YE    1
ZM    1
ZW    1
Name: count, Length: 188, dtype: int64

In [36]:
# Ejercicio 7: Verifica si hay valores nulos en el conjunto de datos.

df_mundo.isna().sum()

Country                   0
Density\n(P/Km2)          0
Abbreviation              7
Agricultural Land( %)     7
Land Area(Km2)            1
Armed Forces size        24
Birth Rate                6
Calling Code              1
Capital/Major City        3
Co2-Emissions             7
CPI                      17
CPI Change (%)           16
Currency-Code            15
Fertility Rate            7
Forested Area (%)         7
Gasoline Price           20
dtype: int64

In [39]:
round(df_mundo.isna().sum()/df_mundo.shape[0]*100,2)

Country                   0.00
Density\n(P/Km2)          0.00
Abbreviation              3.59
Agricultural Land( %)     3.59
Land Area(Km2)            0.51
Armed Forces size        12.31
Birth Rate                3.08
Calling Code              0.51
Capital/Major City        1.54
Co2-Emissions             3.59
CPI                       8.72
CPI Change (%)            8.21
Currency-Code             7.69
Fertility Rate            3.59
Forested Area (%)         3.59
Gasoline Price           10.26
dtype: float64

In [40]:
# Ejercicio 8: Verifica si hay valores no nulos en el conjunto de datos.

df_mundo.notnull().sum()

Country                  195
Density\n(P/Km2)         195
Abbreviation             188
Agricultural Land( %)    188
Land Area(Km2)           194
Armed Forces size        171
Birth Rate               189
Calling Code             194
Capital/Major City       192
Co2-Emissions            188
CPI                      178
CPI Change (%)           179
Currency-Code            180
Fertility Rate           188
Forested Area (%)        188
Gasoline Price           175
dtype: int64

In [41]:
round(df_mundo.notnull().sum()/df_mundo.shape[0]*100,2)

Country                  100.00
Density\n(P/Km2)         100.00
Abbreviation              96.41
Agricultural Land( %)     96.41
Land Area(Km2)            99.49
Armed Forces size         87.69
Birth Rate                96.92
Calling Code              99.49
Capital/Major City        98.46
Co2-Emissions             96.41
CPI                       91.28
CPI Change (%)            91.79
Currency-Code             92.31
Fertility Rate            96.41
Forested Area (%)         96.41
Gasoline Price            89.74
dtype: float64

In [42]:
# Ejercicio 9: Muestra información general sobre el conjunto de datos.

df_mundo.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                195 non-null    str
 1   Density
(P/Km2)        195 non-null    str
 2   Abbreviation           188 non-null    str
 3   Agricultural Land( %)  188 non-null    str
 4   Land Area(Km2)         194 non-null    str
 5   Armed Forces size      171 non-null    str
 6   Birth Rate             189 non-null    float64
 7   Calling Code           194 non-null    float64
 8   Capital/Major City     192 non-null    str
 9   Co2-Emissions          188 non-null    str
 10  CPI                    178 non-null    str
 11  CPI Change (%)         179 non-null    str
 12  Currency-Code          180 non-null    str
 13  Fertility Rate         188 non-null    float64
 14  Forested Area (%)      188 non-null    str
 15  Gasoline Price         175 non-null    str
dtypes: float64(3), str(13)
memory usage: 24.5 KB

In [ ]:
# Ejercicio 10: Elimina una columna específica (por ejemplo, "Armed Forces size").

df_mundo_limpio = df_mundo.drop(columns="Armed Forces size") # df_mundo_limpio = df_mundo.drop(columns=["Armed Forces size"])

In [45]:
df_mundo.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [44]:
df_mundo_limpio.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [47]:
# Ejercicio 11: Selecciona las columnas numéricas del conjunto de datos y muestra sus estadísticas descriptivas básicas.
# Para esto tendréis que usar el método '.describe()', su documentación la tenéis aquí:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html.
# DataFrame.describe (percentiles=None,include=None,exclude=None)​

df_mundo.describe().T

,count,mean,std,min,25%,50%,75%,max
Birth Rate,189.0,20.214974,9.945774,5.90,11.300,17.950,28.7500,46.08
Calling Code,194.0,360.546392,323.236419,1.00,82.500,255.500,506.7500,1876.00
Fertility Rate,188.0,2.698138,1.282267,0.98,1.705,2.245,3.5975,6.91