In [41]:
import numpy as np
import pandas as pd
import random

# Es el turno de los DataFrames:

    - Crea un array de dos dimensiones con 4 filas y 3 columnas.
    - Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
    - Descarga el archivo "medallas" y carga el DataFrame.
    - Usando el loc extrae todas las columnas de la fila de Tailandia.
    - Usando el loc extrae todas las columnas de China e Irán.
    - Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
    - Usando el iloc extrae la información de la India. Devolved todas las columnas.
    - Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
    - Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

    Contesta a las siguientes preguntas:

        - ¿Qué país consiguió más de 200 medallas de oro?
        - ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
        - ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

    - Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [4]:
# Crea un array de dos dimensiones con 4 filas y 3 columnas.

array1 = np.random.randint(0,50,(4,3))

array1

array([[37, 42,  2],
       [48, 11, 44],
       [38, 20, 31],
       [15, 27, 20]], dtype=int32)

In [5]:
# Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_array1 = pd.DataFrame(array1,columns=["España","Francia","Italia"])

df_array1

   España  Francia  Italia
0      37       42       2
1      48       11      44
2      38       20      31
3      15       27      20

In [10]:
#Descarga el archivo "medallas" y carga el DataFrame.

df_medallas = pd.read_csv("medallas.csv",index_col=0)

df_medallas.head(10)

               País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [11]:
#Usando el loc extrae todas las columnas de la fila de Tailandia.

df_medallas.loc[7]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [16]:
#Usando el loc extrae todas las columnas de China e Irán.

df_medallas.loc[1:4:3]

    País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [22]:
#Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

df_medallas.loc[1:4:3][["Oro", "Plata","Bronce"]]

    Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

In [23]:
df_medallas.head(10)

               País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [26]:
# Usando el iloc extrae la información de la India. Devolved todas las columnas.

df_medallas.iloc[5]

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [27]:
df_medallas.loc[6]

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [30]:
# Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

df_medallas.iloc[1::2]

               País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [31]:
# Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

df_medallas.iloc[1::2][["Oro", "Plata","Bronce"]]

     Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [34]:
# ¿Qué país consiguió más de 200 medallas de oro? 

maskOro = df_medallas["Oro"] > 200

maskOro

df_medallas[maskOro].head(10)

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [35]:
#¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

maskPlata = df_medallas["Plata"] > 1000

maskPlata

df_medallas[maskOro & maskPlata].head(10)

    País   Oro  Plata  Bronce
2  Japón  1032   1037     985

In [36]:
#¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

maskBronce = df_medallas["Bronce"] > 700

maskBronce

df_medallas[maskOro | maskBronce].head(10)

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [38]:
#Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

ColumTotal = df_medallas["Oro"] + df_medallas["Plata"] + df_medallas["Bronce"]

ColumTotal

df_medallas["Total_medallas"] = ColumTotal

df_medallas.head(10)

               País   Oro  Plata  Bronce  Total_medallas
1             China  1473    994     720            3187
2             Japón  1032   1037     985            3054
3     Corea del Sur   745    663     827            2235
4              Irán   179    181     197             557
5        Kazajistán   155    158     224             537
6             India   154    202     315             671
7         Tailandia   132    175     278             585
8         Indonesia   112    131     240             483
9      China Taipéi    99    144     276             519
10  Corea del Norte    91    120     235             446

## SERIES

In [49]:
'''Crea dos listas:

    Una que se llame "valores" que tenga 7 números aleatorios.

    Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.'''

valores = [random.randint(0, 50) for x in range(7)]

print(valores)

indices = ["Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo"]

print(indices)

[47, 2, 30, 44, 29, 8, 10]
['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']

In [54]:
#A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

semanaSerie = pd.Series(valores,index=indices)

display(semanaSerie)

Lunes        47
Martes        2
Miercoles    30
Jueves       44
Viernes      29
Sabado        8
Domingo      10
dtype: int64

In [67]:
#A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. 
# Más información sobre este método https://www.programiz.com/python-programming/methods/built-in/zip.

result = zip(indices, valores)
semanaDiccionario = dict(result)


print(semanaDiccionario)

{'Lunes': 47, 'Martes': 2, 'Miercoles': 30, 'Jueves': 44, 'Viernes': 29, 'Sabado': 8, 'Domingo': 10}

In [68]:
#Crea una Serie con el diccionario creado en el punto anterior.

serie_semana = pd.Series(semanaDiccionario)

serie_semana.head()

Lunes        47
Martes        2
Miercoles    30
Jueves       44
Viernes      29
dtype: int64

In [69]:
#¿Qué forma tiene esta última Serie?

serie_semana.shape

(7,)

In [70]:
#¿Qué tipo de datos tiene?

serie_semana.dtype

dtype('int64')

In [71]:
#¿Qué tamaño tiene?

serie_semana.size

7

In [72]:
#¿Cuáles son los índices de la Serie?

serie_semana.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado',
       'Domingo'],
      dtype='str')

In [73]:
#¿Y los values?

serie_semana.values

array([47,  2, 30, 44, 29,  8, 10])

In [75]:
serie_semana.head()

Lunes        47
Martes        2
Miercoles    30
Jueves       44
Viernes      29
dtype: int64

In [76]:
#Extrae el valor para el índice "lunes"

serie_semana.loc["Lunes"]

np.int64(47)

In [77]:
#Extrae el valor para el índice "lunes", "martes" y "miércoles".

serie_semana.iloc[:3]

Lunes        47
Martes        2
Miercoles    30
dtype: int64

In [81]:
#Extrae el valor para el índice "lunes" y "domingo".

serie_semana.iloc[0::6]

Lunes      47
Domingo    10
dtype: int64

In [84]:
serie_semana.loc[["Lunes","Domingo"]]

Lunes      47
Domingo    10
dtype: int64

In [85]:
serie_semana.iloc[[0,6]]

Lunes      47
Domingo    10
dtype: int64

# Más ejercicios de loc e iloc

In [86]:
worldData = pd.read_csv("world-data-2023_part1.csv",index_col=0)

worldData.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [87]:
#Selecciona todas las columnas de las filas 2 a 4 (inclusive) utilizando loc.

worldData.loc[2:4:]

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [89]:
# Utilizando loc, filtra el conjunto de datos para mostrar solo las filas donde la densidad (columna "Birth Rate") es mayor a 30.

maskDensidad = worldData["Birth Rate"] > 30

worldData.loc[maskDensidad].head(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97
18,Benin,108,BJ,33.30%,"112,622","12,000",36.22,229.0,Porto-Novo,"6,476",110.71,-0.90%,XOF,4.84,37.80%,$0.72
26,Burkina Faso,76,BF,44.20%,"274,200","11,000",37.93,226.0,Ouagadougou,"3,418",106.58,-3.20%,XOF,5.19,19.30%,$0.98
27,Burundi,463,BI,79.20%,"27,830","31,000",39.01,257.0,Bujumbura,495,182.11,-0.70%,BIF,5.41,10.90%,$1.21

In [92]:
#Utilizando loc selecciona las columnas "Country" y "Capital/Major City" de las filas donde el porcentaje de tierra agrícola (columna "Fertility Rate") es superior al 3.

maskAgricola = worldData["Fertility Rate"] > 3

worldData.loc[maskAgricola][["Country","Capital/Major City"]].head(5)

         Country Capital/Major City
0    Afghanistan              Kabul
2        Algeria            Algiers
4         Angola             Luanda
18         Benin         Porto-Novo
26  Burkina Faso        Ouagadougou

In [94]:
worldData.iloc[0:4].head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51

In [103]:
#Selecciona todas las filas de las columnas 0 a 4 (excluyendo la columna 4) utilizando iloc.

worldData.iloc[::,[0,1,2,3]]

         Country Density\n(P/Km2) Abbreviation Agricultural Land( %)
0    Afghanistan               60           AF                58.10%
1        Albania              105           AL                43.10%
2        Algeria               18           DZ                17.40%
3        Andorra              164           AD                40.00%
4         Angola               26           AO                47.50%
..           ...              ...          ...                   ...
190    Venezuela               32           VE                24.50%
191      Vietnam              314           VN                39.30%
192        Yemen               56           YE                44.60%
193       Zambia               25           ZM                32.10%
194     Zimbabwe               38           ZW                41.90%

[195 rows x 4 columns]

In [108]:
#Selecciona todas las filas de las columnas 0 a 4 (excluyendo la columna 4) utilizando iloc.

worldData.iloc[::,0:4]

         Country Density\n(P/Km2) Abbreviation Agricultural Land( %)
0    Afghanistan               60           AF                58.10%
1        Albania              105           AL                43.10%
2        Algeria               18           DZ                17.40%
3        Andorra              164           AD                40.00%
4         Angola               26           AO                47.50%
..           ...              ...          ...                   ...
190    Venezuela               32           VE                24.50%
191      Vietnam              314           VN                39.30%
192        Yemen               56           YE                44.60%
193       Zambia               25           ZM                32.10%
194     Zimbabwe               38           ZW                41.90%

[195 rows x 4 columns]

In [110]:
#Encuentra el valor en la fila 2 y columna 7 utilizando iloc.

worldData.iloc[1,7]

np.float64(355.0)

In [112]:
#Selecciona todas las filas para las columnas 0, 2, y 5 utilizando iloc.

worldData.iloc[::,[0,2,5]].head()

       Country Abbreviation Armed Forces size
0  Afghanistan           AF           323,000
1      Albania           AL             9,000
2      Algeria           DZ           317,000
3      Andorra           AD               NaN
4       Angola           AO           117,000

In [113]:
worldData.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [114]:
#Encuentra el valor de "Gasoline Price" para el país cuya abreviatura es "AL" utilizando loc.

maskAbr = worldData["Abbreviation"] == "AL"
worldData.loc[maskAbr,"Gasoline Price"].head()

1    $1.36
Name: Gasoline Price, dtype: str